version: '3.1'
services:
  web:
    platform: linux/amd64
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "9001:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - ODOO_RC=/etc/odoo/odoo.conf

  db:
    platform: linux/amd64
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
